# Routers
r1[0]="CD_R1"
r2[0]="CD_R1"
r2[1]="CD_R2"
r3[0]="CD_R2"
r3[1]="CD_R3"
r4[0]="CD_R3"

# Lama Net
srv[0]="CD_L1"
r1[1]="CD_L1"
pc4[0]="CD_L2"
r1[2]="CD_L2"

# Home Net
pc1[0]="CD_H"
pc2[0]="CD_H"
r2[2]="CD_H"

# Digi Net
dns[0]="CD_D1"
s1[2]="CD_D1"
pc3[0]="CD_D2"
s2[2]="CD_D2"
s1[1]="CD_D3"
s2[1]="CD_D3"
s1[0]="CD_D4"
s3[1]="CD_D4"
s2[0]="CD_D5"
s3[2]="CD_D5"
s3[0]="CD_D6"
r4[1]="CD_D6"

# Set the desired image
dns[image]="telkom_labor"
pc1[image]="telkom_labor"
pc2[image]="telkom_labor"
pc3[image]="telkom_labor"
pc4[image]="telkom_labor"
r1[image]="telkom_labor"
r2[image]="telkom_labor"
r3[image]="telkom_labor"
r4[image]="telkom_labor"
s1[image]="telkom_labor"
s2[image]="telkom_labor"
s3[image]="telkom_labor"
srv[image]="telkom_labor"
