LAB_DESCRIPTION="IPv4, SSH, ARP, Static route, DNS, DHCP, OSPF, Iptables"
LAB_VERSION=1.0
LAB_AUTHOR="Ferenc Orosi"

r1[0]="r1r5"
r1[1]="r1r2"
r1[2]="r1r3"
r1[3]="r1r4"
r1[image]="telkom_labor"

r2[0]="r1r2"
r2[1]="r2web1"
r2[image]="telkom_labor"

r3[0]="r1r3"
r3[1]="pc1r3"
r3[2]="pc2r3"
r3[image]="telkom_labor"

r4[0]="r1r4"
r4[1]="r4sw1"
r4[2]="r4sw2"
r4[image]="telkom_labor"

r5[0]="r5r6"
r5[1]="r5r7"
r5[2]="r5r8"
r5[3]="r1r5"
r5[image]="telkom_labor"

r6[0]="r6web2"
r6[1]="r5r6"
r6[image]="telkom_labor"

r7[0]="pc3r7"
r7[1]="pc4r7"
r7[2]="r5r7"
r7[image]="telkom_labor"

r8[0]="dns2r8"
r8[1]="r5r8"
r8[image]="telkom_labor"

sw1[0]="r4sw1"
sw1[1]="sw1sw3"
sw1[2]="sw1sw4"
sw1[3]="sw1sw5"
sw1[4]="sw1sw2"
sw1[image]="telkom_labor"

sw2[0]="r4sw2"
sw2[1]="sw2sw3"
sw2[2]="sw2sw4"
sw2[3]="sw2sw5"
sw2[4]="sw1sw2"
sw2[image]="telkom_labor"

sw3[0]="sw1sw3"
sw3[1]="sw2sw3"
sw3[2]="pc6sw3"
sw3[3]="sw3sw4"
sw3[image]="telkom_labor"

sw4[0]="sw1sw4"
sw4[1]="sw2sw4"
sw4[2]="pc5sw4"
sw4[3]="sw3sw4"
sw4[4]="sw4sw5"
sw4[image]="telkom_labor"

sw5[0]="sw2sw5"
sw5[1]="sw1sw5"
sw5[2]="dns1sw5"
sw5[3]="sw4sw5"
sw5[image]="telkom_labor"

pc1[0]="pc1r3"
pc1[image]="telkom_labor"

pc2[0]="pc2r3"
pc2[image]="telkom_labor"

pc3[0]="pc3r7"
pc3[image]="telkom_labor"

pc4[0]="pc4r7"
pc4[image]="telkom_labor"

pc5[0]="pc5sw4"
pc5[image]="telkom_labor"

pc6[0]="pc6sw3"
pc6[image]="telkom_labor"

web1[0]="r2web1"
web1[image]="telkom_labor"

web2[0]="r6web2"
web2[image]="telkom_labor"

dns1[0]="dns1sw5"
dns1[image]="telkom_labor"

dns2[0]="dns2r8"
dns2[image]="telkom_labor"

